apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
  namespace: dataforge
data:
  core-site.xml: |
    <?xml version="1.0"?>
    <configuration>
        <property>
            <name>fs.defaultFS</name>
            <value>hdfs://hdfs-namenode:8020</value>
        </property>
    </configuration>

  hdfs-site.xml: |
    <?xml version="1.0"?>
    <configuration>
        <property>
            <name>dfs.replication</name>
            <value>1</value>
        </property>
        
        <property>
            <name>dfs.namenode.name.dir</name>
            <value>file:///data/name</value>
        </property>
        
        <property>
            <name>dfs.datanode.data.dir</name>
            <value>file:///data/data</value>
        </property>
        
        <property>
            <name>dfs.permissions.enabled</name>
            <value>false</value>
        </property>
        
        <property>
            <name>dfs.namenode.rpc-address</name>
            <value>hdfs-namenode:8020</value>
        </property>
        
        <property>
            <name>dfs.namenode.rpc-bind-host</name>
            <value>0.0.0.0</value>
        </property>
        
        <property>
            <name>dfs.namenode.http-address</name>
            <value>hdfs-namenode:9870</value>
        </property>
        
        <property>
            <name>dfs.namenode.http-bind-host</name>
            <value>0.0.0.0</value>
        </property>
    </configuration>